_target_: src.trainers.sae_trainer.SAETrainer

# --- Training Hyperparameters ---
learning_rate: 1e-4
batch_size: 128
num_epochs: 50
l1: 0.0001

# --- DataLoader Parameters ---
num_workers: 4
pin_memory: True 
amp_enabled: True
compile_enabled: True
validate_every_n_epochs: 1 